/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface NkStockFinder {}
  interface NkStockFinderAttributes extends StencilHTMLAttributes {
    'onNksymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface NkStockPrice {
    'stockSymbol': string;
  }
  interface NkStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'NkStockFinder': Components.NkStockFinder;
    'NkStockPrice': Components.NkStockPrice;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'nk-stock-finder': Components.NkStockFinderAttributes;
    'nk-stock-price': Components.NkStockPriceAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNkStockFinderElement extends Components.NkStockFinder, HTMLStencilElement {}
  var HTMLNkStockFinderElement: {
    prototype: HTMLNkStockFinderElement;
    new (): HTMLNkStockFinderElement;
  };

  interface HTMLNkStockPriceElement extends Components.NkStockPrice, HTMLStencilElement {}
  var HTMLNkStockPriceElement: {
    prototype: HTMLNkStockPriceElement;
    new (): HTMLNkStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'nk-stock-finder': HTMLNkStockFinderElement
    'nk-stock-price': HTMLNkStockPriceElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'nk-stock-finder': HTMLNkStockFinderElement;
    'nk-stock-price': HTMLNkStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
